### ISSUE TITLE
ImportError: cannot import name '_new_site' from 'frappe.commands.site'

### ISSUE THREAD

**Issue by Goeppert** [frappe/frappe_docker#431]
Hi there,  Thanks for putting together this resource.  

I followed your instructions for setting up a single bench install (https://github.com/frappe/frappe_docker/blob/develop/docs/single-bench.md)

And I got the following error:

 ```
ubuntu@eg-7-ssd-bhs1:~/frappe_docker$ sudo docker logs kevin419_site-creator_1 -f
  Attempt 1 to connect to mariadb:3306
  Attempt 2 to connect to mariadb:3306
  Attempt 3 to connect to mariadb:3306
  Attempt 1 to connect to redis-queue:6379
  Attempt 1 to connect to redis-cache:6379
  Attempt 1 to connect to redis-socketio:6379
  Connections OK
  Traceback (most recent call last):
    File "/home/frappe/frappe-bench/commands/new.py", line 5, in <module>
      from frappe.commands.site import _new_site
  ImportError: cannot import name '_new_site' from 'frappe.commands.site' (/home/frappe/frappe- bench/apps/frappe/frappe/commands/site.py)
```

**Comment by Mohamedmahrous995** [comment]
the same issue with me , did you fix it ?

**Comment by smartekIT** [comment]
I confirm, the same with me for the last 2 days and no way to create the site.

**Comment by Thunderbottom** [comment]
Seems like an import path change in the upstream, have sent a pull request to fix this.

**Comment by Thunderbottom** [comment]
Seems like the import path for the `_new_site()` function has changed in the upstream, have sent a pull request to fix this.

**Comment by Mohamedmahrous995** [comment]
i have added the from frappe.installer.site import _new_site but still not working when i connect to browser it gives me internal server error !!!!

**Comment by Thunderbottom** [comment]
Not sure why that would happen. Seems like a separate issue unrelated to this one. If it persists after the pull request is merged, please feel free to open a new issue describing the internal server error

**Comment by smartekIT** [comment]
mate even after the merge, the creator container still gives the same error:'
ImportError: cannot import name '_new_site' from 'frappe.commands.site' (/home/frappe/frappe- bench/apps/frappe/frappe/commands/site.py)

**Comment by Thunderbottom** [comment]
Figured it out, my bad. I hope I can use lack of sleep as an excuse for this one.
